@echo off
echo Serverni to'xtatish...
taskkill /F /IM node.exe 2>nul
echo Prisma client yangilanmoqda...
call npx prisma generate
cd server
echo Server build qilinmoqda...
call npm run build
echo Server ishga tushmoqda...
start npm start
cd ..
echo Frontend ishga tushmoqda...
npm run dev
